### ISSUE TITLE
Lootr

### ISSUE THREAD

**Issue by noobanidus** [spoorn/myLoot#1]
I'm actually in the process of working with someone to port Lootr directly to Fabric. If you're interested in contributing, I'd greatly appreciate your help with it and would absolutely be willing to provide you with a portion of Curse Points.

That said, if you plan on maintaining this as a separate project, I would prefer it if you would make your artwork distinctively unlike Lootr so as not to confuse people as to which project it is.

EDIT: Oh, and for clarity, the addition gem in the texture of the opened chest is to help differentiate it from closed chests for people who have issues with color-blindness.

EDIT 2: And just to clarify, I'm not upset or angry with this mod at all. I'm glad Fabric finally has another alternative to the one linked on the Lootr page.

**Comment by noobanidus** [comment]
> I just wanted to have instanced loot to play with friends on personal servers with the specific features. If someone wants to create better textures for me or I want to change it, then I'd be down, else I don't want to throw away those 5 hours. I put my head down for 3 days to write myLoot because I wanted something exactly like this. I have no intention of competing with or overtaking Lootr in any way and believe both mods can coexist with different set of features

That's totally fine and I absolutely appreciate it. I'm going to link your mod from the Lootr page.

**Comment by spoorn** [comment]
Thanks for understanding, and feel free to use the code as a reference for helping port Lootr over
