### ISSUE TITLE
BetterEnd chests not converted and empty

### ISSUE THREAD

**Issue by Scratchman** [spoorn/myLoot#14]
After adding your mod to our server and flying around the end that's been generated by the fabric  betterend mod, we have found that the betterend chests are not converted but also all of them are empty.
The server has been running for a few weeks and the end was explored for a bit, so we know that chests had contents before we added your mod today.

Log .. https://pastebin.com/C0inp1Mz

**Comment by spoorn** [comment]
I've been aware of this and have a fix in the works.  Will release tomorrow probably

**Comment by spoorn** [comment]
Should be fixed in 2.0+.  Let me know!

**Comment by Scratchman** [comment]
issue was fixed, thanks .. I also found out that some of the betterend chests are empty because they don't have a loot table, but those that do were converted to myloot chest.

Also, fyi, your new json5 file has 2 periods in the name so the old cfg is not being replaced.

**Comment by spoorn** [comment]
Thanks for the catch.  Fixed in latest release, sorry for the bugs.  Coding so late at night really degrades the quality lol
