### ISSUE TITLE
I can't create myloot chest

### ISSUE THREAD

**Issue by Enterenn** [spoorn/myLoot#15]
I have a server for friends and I, and using my loot.

I made a small hub where people will spawn, and in creative mod, i placed a myLoot chest and fill it with some items
But it didn't seemed to work as other players couldn't see anything inside

Any idea ?

**Comment by spoorn** [comment]
The myLoot containers are instanced per player.  If you put items inside the myLoot chest, only you can see those items.  Other players will see their own instance of the chest.  If you want other players to see items you put inside the chest, it has to be generated via the chest's Loot Table, not by manually inserting into the chest inventory.

There are ways to spawn a chest with specific loot inside it via a `/setblock` command I believe, but it's not so straight forward.

myLoot was not intended for ad-hoc customization of the loot per player, so it doesn't easily support what you are trying to do.  I can look into a way for easily generating a myLoot container with some starter loot as an enhancement
