### ISSUE TITLE
when dungeons arise compability?

### ISSUE THREAD

**Issue by AngelTheGamerHD** [spoorn/myLoot#19]
castle structure doesnt have myloot chests

**Comment by spoorn** [comment]
What versions of myLoot and WhenDungeonsArise do you have?  Minecraft/Fabric version?  And which structure in WhenDungeonsArise.  It's been working for me so far

**Comment by AngelTheGamerHD** [comment]
fabric mylot 1.7.1 
DungeonsArise-1.18.1-2.1.49d

**Comment by spoorn** [comment]
It's been a while, try the later versions.  Please reopen if this issue persists
