### ISSUE TITLE
[1.18.2/1.19] Artifact's Mimic Compat

### ISSUE THREAD

**Issue by ConqAra** [spoorn/myLoot#21]
Artifact's mimics will just show as normal chests, which is obvious that their mimics. Is there a way to add compat for mimic chests from artifacts with myloot?

**Comment by spoorn** [comment]
I haven't looked at Artifact's code, but I assume the mimic is an actual LivingEntity, not a BlockEntity.  The only way I could add compat is by replacing the textures of the mimic entity, or creating a new Mimic entity with myLoot textures.  The first is easier, but I don't have experience in adding mobs to the game so I'd have to dig into it

**Comment by ConqAra** [comment]
> We already have support for lootr, shouldn't be hard to do the same for myloot.

The issue I've posted in artifacts github said they already have added support, just so you know

**Comment by spoorn** [comment]
For tracking, here's the Issue: https://github.com/ochotonida/artifacts/issues/153

They added support for Lootr, so they may be able to add support for myLoot easily

**Comment by florensie** [comment]
Support added in this commit: https://github.com/florensie/artifacts-fabric/commit/a88a154cecd3dad5952d274eb655819fd90a4f39

You can close this issue ;)
