### ISSUE TITLE
[1.19.2] watchdog + MyLoot

### ISSUE THREAD

**Issue by itsdinkd** [spoorn/myLoot#26]
Hey spoorn, i put this in a closed issue 2 weeks ago so wanted to open a new issue so it doesnt get lost.

I cannot give you any reproduction steps unfortunately but these crashes are very common in one of our servers. 

https://mclo.gs/GKCLiWX
https://mclo.gs/moRAP4h
https://mclo.gs/MLgN9Tz

**Comment by AnasJS99** [comment]
whenever i go to broken ships from normal minecraft structures. it crashes the server.
