### ISSUE TITLE
Server Crash with latest build

### ISSUE THREAD

**Issue by Gamerbolts** [spoorn/myLoot#3]
I updated Myloot and Spoornpacks on my modpack. I tried to load up the server and it keeps saying Failed to start, no crash log but here is the latest log. Any help is appreciated, Thanks!
[latest.log](https://github.com/spoorn/myLoot/files/8158368/latest.log)

**Comment by spoorn** [comment]
Will have a fix for this tonight

**Comment by spoorn** [comment]
Please try the latest myLoot (1.4.1) and SpoornPacks (3.5.1).  Let me know if there are still issues

**Comment by Gamerbolts** [comment]
That worked. Thanks so much for the quick fix!
