### ISSUE TITLE
[Feature Request] Whitelist / Blacklist

### ISSUE THREAD

**Issue by itsdinkd** [spoorn/myLoot#4]
Requesting features that would allow modpack devs, or anyone really a way to blacklist and/or whitelist giving complete control of the mod and how it affects things via the following;

**
- Mods _example: [ "graveyard" ]_
- Structures _example: [ "dungeonsarise:heavens_challenger" ]_
- Loot tables _example: [ "modid:loot/factory" ]_
- Dimensions _example: [ "minecraft:the_nether", "minecraft:the_end" ]_
- Chests _example: [ "minecraft:shulker", "minecraft:chest_cart", "urn:urn" ]_
**

Config Example:
```
#list of mods loot tables that shouldn't be converted into MyLoot chests
modBlacklist = [
],
#list of structures that should not have myloot chests
structureBlacklist = [
],
#list of loot tables that shouldn't be be converted into MyLoot chests
lootTableBlacklist = [
],
#list of dimensions that shouldn't have myloot chests
dimensionBlacklist = [
],
#list of chests that shouldn't convert into myloot chests
chestBlacklist = [
],
#Turn mod blacklist into whitelist
modWhitelist = false,
#Turn mod blacklist into whitelist
structureWhitelist = false,
#Turn mod blacklist into whitelist
lootTableWhitelist = true,
#Turn mod blacklist into whitelist
dimensionWhitelist = true,
#Turn mod blacklist into whitelist
chestWhitelist = true,
```

**Comment by spoorn** [comment]
Added a bunch of config options in 2.0+.  Let me know by reopening this issue or creating a new one for other features you'd like
