### ISSUE TITLE
[Feature Request] Indestructible 

### ISSUE THREAD

**Issue by itsdinkd** [spoorn/myLoot#5]
Add option to allow or disallow players from destroying Myloot blocks

**Comment by spoorn** [comment]
added in https://github.com/spoorn/myLoot/commit/cea36802a6dbd20b75fb4b25ed45509597ab1b21

**Comment by alex99ata** [comment]
Hello, how to use it?

**Comment by alex99ata** [comment]
> Add option to allow or disallow players from destroying Myloot blocks

How did you used it bro?

**Comment by spoorn** [comment]
it's an option in `config/myloot.json5`

you can set this field to false: https://github.com/spoorn/myLoot/blob/main/config-documentation.json5#L8

**Comment by spoorn** [comment]
That's a bug, you could have submitted a new Issue for that.  I'll have a fix out soon

**Comment by spoorn** [comment]
Fixed in https://github.com/spoorn/myLoot/commit/7737b36caff30b4de3b26b364c870de480c6d103

**Comment by alex99ata** [comment]
Thanks man!
