### ISSUE TITLE
[Feature Request] Random Seed on or Off

### ISSUE THREAD

**Issue by itsdinkd** [spoorn/myLoot#6]
Requesting to add a config option to allow or disallow random seed generation or static seed for each myloot chest conversion. 

This way modpack devs/players can choose if they want each chest to generate new loot from that loot table for each player who opens said chest, or to always have the same loot for that chest.

**Comment by spoorn** [comment]
Added in https://github.com/spoorn/myLoot/commit/bfd96273ee99ddfb7d75f902fadf603e79ec6c5f
