### ISSUE TITLE
[1.18.1] Reports of Missing Loot from Repurposed Structures

### ISSUE THREAD

**Issue by itsdinkd** [spoorn/myLoot#9]
I am getting reports of players opening chests in Repurposed Structures and nothing is in them. these chests are MyLoot chests. 

This is a great use case for #4 as I could blacklist the structures until a fix is released :D 

MC: 1.18.1
MyLoot: v1.7.1

**Comment by spoorn** [comment]
Do you have any logs from when the loots don't generate anything?  I had tested with Repurposed Structures and didn't find any problems.

Also, I plan to work on the other features, but haven't yet found the time

**Comment by itsdinkd** [comment]
I do not have logs. next time a player reports this, I will make sure to grab the latest.log from them. I didn't know it would generate a debug log if no loot was found.

**Comment by spoorn** [comment]
Same issue as https://github.com/spoorn/myLoot/issues/14 Should be fixed in 2.0+
